=== 1proprogrammerchant/cumulus/docs/schemas/collections_config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Collection Configuration",
  "description": "Describes the workflows, tasks, schedule, and other options for ingesting a collection.",
  "type": "object",
  "properties": {
    "id": {
      "description": "An id used to identify this configuration.",
      "type": "string",
      "minLength": 1
    },
    "trigger": {
      "$ref": "#/definitions/TriggerType"
    },
    "meta": {
      "$ref": "#/definitions/MetaType"
    },
    "task_config": {
      "$ref": "#/definitions/TaskConfigType"
    },
    "workflows": {
      "$ref": "#/definitions/WorkflowsType"
    }
  },
  "required": ["id", "meta", "task_config", "workflows"],
  "additionalProperties": false,
  "definitions": {
    "positiveInteger": {
      "type": "integer",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "TriggerType": {
      "description": "Defines the schedule for triggering the collection. ",
      "type": "object",
      "properties": {
        "interval_sec": {
          "description": "Defines how frequently in seconds this collection is triggered to run.",
          "$ref": "#/definitions/positiveInteger"
        },
        "workflow": {
          "description": "The name of a workflow to execute when the trigger fires.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "MetaType": {
      "description": "Defines meta-configuration information about the particular collection being processed. These can contain any data that is specific to the collection.",
      "type": "object"
    },
    "TaskConfigType": {
      "description": "Defines configuration for tasks that are part of a workflow as a map of task name to a JSON object containing configuration settings.",
      "type": "object",
      "minProperties": 1,
      "patternProperties": {
        "^[0-9a-zA-Z_\\-.]+$": {
          "description": "Any configuration properties are permitted here for the task.",
          "type": "object"
        }
      },
      "additionalProperties": false
    },
    "WorkflowsType": {
      "description": "Defines a set of named workflows as a JSON object of workflow name to a workflow defined in the AWS Step Function States Language.",
      "type": "object",
      "minProperties": 1,
      "patternProperties": {
        "^[0-9a-zA-Z_\\-.]+$": {
          "description": "This should be a AWS Step Function compliant with the Amazon States Language defined here http://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language.html#amazon-states-language",
          "type": "object"
        }
      },
      "additionalProperties": false
    }
  }
}

=== 1proprogrammerchant/cumulus/docs/schemas/example-data/example-collection.json
{
  "id": "VNGCR_LQD_C1",
  "trigger": {
    "interval_sec": 900,
    "workflow": "discover_VNGCR_LQD_C1"
  },
  "meta": {
    "collection": "VNGCR_LQD_C1",
    "parameterName": "VNGCR_LQD_I1-M4-M3_NRT",
    "epsg": 4326,
    "zoom": 9
  },
  "task_config": {
    "DiscoverHttpTiles": {
      "type": "apache-index",
      "connections": 10,
      "root": "https://lance3.modaps.eosdis.nasa.gov/imagery/elements/VIIRS/{meta.collection}/",
      "match": "https://lance3.modaps.eosdis.nasa.gov/imagery/elements/VIIRS/{meta.collection}/{_}/{jday}/{file}.{ext}",
      "required": [
        {
          "group": "file",
          "prop": "ext",
          "values": [
            "jgw",
            "jpg",
            "txt"
          ]
        }
      ],
      "group_by": "VIIRS/{meta.collection}/{match.jday}",
      "add_meta": {
        "key": "VIIRS/{meta.collection}/{match.jday}",
        "date": {
          "type": "date",
          "value": "{match.jday}"
        }
      }
    },
    "SyncHttpUrls": {
      "connections": 5,
      "output": {
        "bucket": "{resources.buckets.private}",
        "key_prefix": "sources/EPSG{meta.epsg}/{meta.key}"
      }
    },
    "MRFGen": {
      "mrfgen": {
        "mrf_compression_type": "JPEG",
        "source_epsg": "{meta.epsg}",
        "mrf_merge": false,
        "mrf_nocopy": true,
        "overview_resampling": "average",
        "resize_resampling": "average",
        "parameter_name": "{meta.parameterName}"
      },
      "output": {
        "bucket": "{resources.buckets.public}",
        "key_prefix": "EPSG{meta.epsg}/{meta.collection}/{meta.date.year}"
      }
    }
  },
  "workflows": {
    "discover_VIIRS": {
      "Comment": "VIIRS Discovery",
      "StartAt": "DiscoverHttpTiles",
      "States": {
        "DiscoverHttpTiles": {
          "Type": "Task",
          "Resource": "TaskDiscoverHttpTilesFn",
          "Next": "TriggerIngestStateMachine"
        },
        "TriggerIngestStateMachine": {
          "Type": "Task",
          "Resource": "TaskTriggerIngestFn",
          "End": true
        }
      }
    },
    "ingest_VIIRS": {
      "Comment": "VIIRS Ingest",
      "StartAt": "SyncHttpUrls",
      "States": {
        "SyncHttpUrls": {
          "Type": "Task",
          "Resource": "TaskSyncHttpUrlsFn",
          "Next": "ChooseSyncContinuation"
        },
        "ChooseSyncContinuation": {
          "Type": "Choice",
          "Choices": [
            {
              "Variable": "$.exception",
              "StringEquals": "NotNeeded",
              "Next": "NoUpdates"
            },
            {
              "Variable": "$.exception",
              "StringEquals": "Incomplete",
              "Next": "SyncHttpUrls"
            },
            {
              "Variable": "$.exception",
              "StringEquals": "None",
              "Next": "MRFGen"
            }
          ],
          "Default": "UnhandledSyncError"
        },
        "UnhandledSyncError": {
          "Type": "Fail",
          "Cause": "Unhandled Sync Error"
        },
        "MRFGen": {
          "Type": "Task",
          "Resource": "ActivityGenerateMrf",
          "End": true
        },
        "MethodNotFound": {
          "Type": "Fail",
          "Cause": "Ingest Method Not Found"
        },
        "NoUpdates": {
          "Type": "Pass",
          "Result": "No Updates Necessary",
          "End": true
        }
      }
    }
  }
}
